source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target "AdvancedExample" do
  pod 'GoogleAds-IMA-iOS-SDK', '= 3.6.1'
  pod 'google-cast-sdk', '~>3.2.0'
  pod 'YouboraIMAAdapter', :path => '/Users/Enrique/XcodeProjects/YouboraIMAAdapter'
  pod 'YouboraAVPlayerAdapter'
end
